### ISSUE TITLE
[CI] build a public gerrit for code review

### ISSUE THREAD

**Issue by arthur-wangfeng** [Hybrid-Cloud/hybrid_cloud#15]
requirements:
1. support access from public network
2. support code review for all github projects in Hybrid-Cloud team

due time: Dec 18th

**Comment by arthur-wangfeng** [comment]
Gerrit can be accessed from public network now.
Need more configurations, e.g. user account, related project

**Comment by drormizrachi** [comment]
Whether it is ready, please let us know so we can test it from T-DIV

**Comment by arthur-wangfeng** [comment]
merge to "Build a CI Enviroment task"
