### ISSUE TITLE
[CI] Clean projects in github team hybrid_cloud

### ISSUE THREAD

**Issue by arthur-wangfeng** [Hybrid-Cloud/hybrid_cloud#16]
delete all useless projects github team hybrid_cloud.

**Comment by nkzhangni** [comment]
build a empty dir for horzion, zhangshen confirm with chenyujie to upload the code

**Comment by arthur-wangfeng** [comment]
> build a empty dir for horzion, zhangshen confirm with chenyujie to upload the code

Done!

**Comment by arthur-wangfeng** [comment]
Merged to https://github.com/Hybrid-Cloud/hybrid_cloud/issues/17
