### ISSUE TITLE
Decouple network features with compute features.

### ISSUE THREAD

**Issue by arthur-wangfeng** [Hybrid-Cloud/hybrid_cloud#19]
make connectivity team can deliver e2e features, without an extra guy from computing team to integrate it.

**Comment by arthur-wangfeng** [comment]
split to 2 issues. (Zhangsen, Dror)

**Comment by arthur-wangfeng** [comment]
Wangjun will contact with eshed to disscuss this issue

**Comment by wuyanhua** [comment]
zhangsen will give a solution and discuss with dror\lili before next Monday(2-29)

**Comment by arthur-wangfeng** [comment]
provide plug_vif implementation, one for agent and the other for agentless.  chosen by nova configuation
