### ISSUE TITLE
give a HLD of agent with container solution

### ISSUE THREAD

**Issue by arthur-wangfeng** [Hybrid-Cloud/hybrid_cloud#2]
**description**: T-div give a HLD of agent with container solution, include: architecture, docker or LXC, requirements to computing team.

**due date**: 

**assignee**: Eshed/Dror

**from**: meeting on 2015/11/17

**Comment by eshedg** [comment]
added the HyperVM blueprint to the git
https://github.com/Hybrid-Cloud/hybrid_cloud/tree/master/doc/source/hypervm

**Comment by arthur-wangfeng** [comment]
created  a new  task to review it:
https://github.com/Hybrid-Cloud/hybrid_cloud/issues/12

close this issue.
