### ISSUE TITLE
Document everything

### ISSUE THREAD

**Issue by arthur-wangfeng** [Hybrid-Cloud/hybrid_cloud#23]
-  Introduction
  - Solution background                   -- 李力
-  Features and Roadmaps
  - Hybrid Solution Project working guide   -- 王烽 (介绍我们的项目运作和管理方式，说明特性提交流程、代码提交流程、CI/CD流程、外部项目的集成流程)
  - Hybrid Cloud Features
- Meeting Minutes
  - Weekly Meeting (2015.12.01)
  - Weekly Meeting (2015.11.24)
  - Weekly Meeting (2015.11.16~17)
  - Weekly Meeting (2015.11.4)
  - 尽量补充前期的weekly meeting内容   -- 王烽
- Alternative Analyse
  - LXC Solution Analyse
  - Agent API Analyse
  - Hybrid Cloud Networking Analyse
  - Hybrid Cloud As a Service Portal
  - How to add OpenStack private cloud
  - How to add vCloud private cloud
  - 前期的备选概念胶片转换成wiki页面（有几个写几个）   -- 王烽
  - 前期的备选概念胶片转换成wiki页面（有几个写几个）   -- 张森
  - 前期的备选概念胶片转换成wiki页面（有几个写几个）   -- 殷薇
- Solution Design
  - Solution Architecture                   -- 李力
  - AWS Jacket                             -- 张森
  - vCloud Jacket                             -- 张森
  - FS Gateway                             -- 张森
  - HWS Gateway                          -- 张森（内源）
  - Cloud Scaling                          -- 张森
  - Cloud Management Service (CMS)       -- 张森
  - V2V Service(Birdie)                     -- 张妮 (刘玲)
  - V2V Gateway (Open Source version)     -- 张妮 (刘玲)
  - DPaaS  (Smaug)                       -- 殷薇 ( 直接简单说明集成关系，链接到Smaug网站即可)
  - Cloud Volume Restore                   --殷薇 ( 直接描述基于Cinder扩展跨云backup/restore能力)
  - Storage Gateway (Ceph version)         -- 殷薇
  - Cloud Hyper Network (Bambu)           --王烽负责和Dror沟通
  - Hyper Switch (Open Source version)     -- 王烽负责和Dror沟通
  - Board Gateway (Open Source version)   -- 王烽负责和Dror沟通
  - WAN Vitulization (WANV)                -- 王烽负责和Dror沟通
- API Reference
  - Migration accross clouds
  - FS Gateway API v1.0
  - Cloud Manager Service API v1.0
  - HWS Gateway API v1.0                          -- 张森（内源）
  - Cloud Scaling API v1.0                          -- 张森
  - Cloud Management Service (CMS) API v1.0       -- 张森
  - V2V Service(Birdie) API v1.0                     -- 张妮 (刘玲)
  - DPaaS  (Smaug) API v1.0                       -- 殷薇 ( 直接简单说明集成关系，链接到Smaug网站即可)
  - Cloud Volume Restore API v1.0                   --殷薇 ( 直接描述基于Cinder扩展跨云backup/restore能力)
  - Cloud Hyper Network (Bambu) API v1.0           --王烽负责和Dror沟通 )
- Testing Report
  - CI Test Report                                  -- 张森
  - Storage Gateway Performance Test Report       -- 殷薇

**Comment by arthur-wangfeng** [comment]
@drormizrachi . 

we can't see these wiki:

Cloud Hyper Network (Bambu) --王烽负责和Dror沟通
Hyper Switch (Open Source version) -- 王烽负责和Dror沟通
Board Gateway (Open Source version) -- 王烽负责和Dror沟通

Put them online ASAP, Thanks

**Comment by drormizrachi** [comment]
Please review: https://github.com/Hybrid-Cloud/hybrid_cloud
