### ISSUE TITLE
choose openstack basic version

### ISSUE THREAD

**Issue by arthur-wangfeng** [Hybrid-Cloud/hybrid_cloud#28]
If we use J version, the missed features:
1. L2 gateway. L version
2. dragonflow, L version or later
3. hyperswitch, L or later.
4. multi-az LB, K version. (need cascading upgrated )
5. kuryr, M version
5.

**Comment by wuyanhua** [comment]
wuyanhua check the progress of L version upgrade in fusionsphere6.1(xuchengwu).

**Comment by wuyanhua** [comment]
Every team estimate the workload of switch to L version.

**Comment by drormizrachi** [comment]
Networking team - Hyper Switch as well as BGW already aligned with Liberty version.

**Comment by arthur-wangfeng** [comment]
switch to liverty
