### ISSUE TITLE
[CI] [Gerrit] multi commits with abandoned ones can not submit

### ISSUE THREAD

**Issue by toddyLee** [Hybrid-Cloud/hybrid_cloud#32]
when a committer posted multiple commits, and abandoned one of them, other commits can not be submitted after reviewed: 
![image](https://cloud.githubusercontent.com/assets/16913478/13133306/04901342-d635-11e5-8765-a1f1b4cf36a7.png)
- committer posts Commit A and B to Gerrit
- then the committer abandons commit A on the Gerrit
- After that the reviewer logon on and approves commit B ( for commit A was abandoned by the committer, only commit B is at open status); but the reviewer can not submit the commit, the "Submit" icon is changed to grey ...
  ![image](https://cloud.githubusercontent.com/assets/16913478/13133401/db14250c-d635-11e5-8e4c-72a1b3507fa0.png)  
  next time the committer run the command "git review", he will get the warning message below:  
  ![image](https://cloud.githubusercontent.com/assets/16913478/13133422/1645d954-d636-11e5-9c83-f7c55b44ad91.png)
  and when run "git status" will get the message:  
  ![image](https://cloud.githubusercontent.com/assets/16913478/13133446/3bd029b8-d636-11e5-8fa8-2b13ba52d409.png)

**Comment by arthur-wangfeng** [comment]
it's a configuration l issue of gerrit, happened in special situation. 
I assign it to Li Liangyu and he is working on this. 
It's not a stopper.
