### ISSUE TITLE
Test connectivity solution data plane performance

### ISSUE THREAD

**Issue by arthur-wangfeng** [Hybrid-Cloud/hybrid_cloud#4]
**\* Split this task into separate tasks ***
#46
#47
#48
#49

Test connectivity solution data plane performance, including a hyperswitch performance evaluation, 

This task include several sub-tasks:
1. Eventually, what we need is a performance test report, which can prove hyper-network solution meet our performance requirements from PDCP: 
   1) x10 scalability/elasticity in the data plane
   2) performance degradation less than 30%
   
   we need to test our final connectivity solution end-to-end, which include agent-container solution, BGW, etc.
2. (Current work) According to WuTianyi's report, ovs running on virtual machine maybe a performance bottleneck. We need test it ASAP, ensure there is no risk to fulfill our performance target.

**And we need test another case more: connectivity performance across subnet, if vms are in different subnet**

**due date**:

**assignee**: Dror/Ayal/Lili

**from**: meeting on 2015/11/16

**Comment by drormizrachi** [comment]
It's on hold (low priority) since our focus is agent based solution

**Comment by arthur-wangfeng** [comment]
Hi all,

In my opinion, what we need is a performance test report, which can prove hyper-network solution meet our performance requirements from PDCP: 
1) x10 scalability/elasticity in the data plane
2) performance degradation less than 20%

we need to test our final connectivity solution end-to-end, which include agent-container solution, BGW, etc.  Of course, we can test it step by step, module by module, but finally we need an end-to-end test.

So, I think fulfill the final solution is higher priority than testing hyper-switch, which is a part of  temporary agent-less solution.

**Comment by drormizrachi** [comment]
Here are the results on AWS:
- No impact on the BW when we're using Hyper Node
- However, in case of stress testing via several VMs, AWS detects it as attack on VM and therefore decrease the BW to ~750Mbps and later to 125Mbps.
- Need to check with AWS support if we can set a special VM as a server which receives a lot of traffic with no reflection on the BW 
- More results will be presented in the weekly meeing

**Comment by drormizrachi** [comment]
![Uploading image.png…]()

**Comment by arthur-wangfeng** [comment]
Dror, Eshed, Thanks for your testing result.

And we need test another case more: connectivity performance across subnet, if vms are in different subnet.

**Comment by drormizrachi** [comment]
Shachar: please test the connectivity performance across 2 subnets

**Comment by snapiri** [comment]
Currently there is no way to test it correctly as every HN assumes there is no other HN on the VPC.
Also, the HN code should change dramatically when the HN will support the VPN solution, so our recommendation is to postpone this to the end of February (after the VPN solution will be comitted).
Also, communication cross-clouds will be limited by the WAN bandwidth which is out of our control.

**Comment by drormizrachi** [comment]
We will do the test step by step depends on the progress of development.
1. HyperSwitch - local testing
2. HyperSwitch+ BGW  - cross cloud testing
3. HyperSwitch+ BGW +WANV - cross cloud testing
