### ISSUE TITLE
[CI]aws上面的卷出现error-deleting状态，此时卷无法删除

### ISSUE THREAD

**Issue by liulongzhu** [Hybrid-Cloud/hybrid_cloud#51]
![image](https://cloud.githubusercontent.com/assets/17536495/15416547/30c88c04-1e7f-11e6-93c8-4286d5b731e6.png)

**Comment by nash-x** [comment]
有2中情况出现了此问题：
1、被级联去删除卷时，会先查询此卷是否存在，如果存在就会去进行删除操作。出问题时，查询到了被级联的卷，而删除时，这个卷没有了。
修复的方式：捕获异常，如果是卷没有了的情况，就不再抛出异常，因为卷已经不存在了，直接返回删除成功。
2、第二种情况是在级联层下发删除操作时，VPN链接不上，导致下发操作超时，引起error_deleting。
这种情况属于基本环境问题，不进行修复。
