### ISSUE TITLE
[CI]用例失败，ssh报错，test_can_create_server_with_max_number_personality_files

### ISSUE THREAD

**Issue by liulongzhu** [Hybrid-Cloud/hybrid_cloud#53]
用例为：
compute.servers.test_servers_operations.HybridAwsServerPersonalityTestJSON.test_can_create_server_with_max_number_personality_files
报错信息：
![image](https://cloud.githubusercontent.com/assets/17536495/15416576/7892e138-1e7f-11e6-90f1-4c6aece62f8e.png)

**Comment by nash-x** [comment]
原因：当前创建虚拟机时，使用的是intrenal_base平面，但是这个平面有很多IP已经被cascaded node 的brcps端口使用，创建虚拟机时，亚马逊DHCP会有可能分配的IP与cascaded node的brcps端口使用的IP重复，导致连接不上。
修复方法：创建虚拟机时，改成了external_api平面。

**Comment by nash-x** [comment]
http://202.96.135.238:8081/#/c/201/

配置文件/etc/nova/nova-compute.conf，此配置项subnet_api = subnet-a2703ad5，需要设置为external_api平面的子网ID。
此配置项改为：rabbit_host_ip_public = 172.29.0.150，改为了api平面的cascaded node的IP
