### ISSUE TITLE
[CI]jacket自动部署后出现aws的nova-compute无法启动

### ISSUE THREAD

**Issue by liulongzhu** [Hybrid-Cloud/hybrid_cloud#55]
![image](https://cloud.githubusercontent.com/assets/17536495/15416613/eb0a49c2-1e7f-11e6-809a-8de423a7d58c.png)

**Comment by nash-x** [comment]
这个问题应该转给罗锐处理，请龙珠转给罗锐。

**Comment by liulongzhu** [comment]
此问题李太安已解决，启动不了是由于上传的代码中有语法问题。
