### ISSUE TITLE
[CI]tempest测试用例失败，HybridDeleteAwsServersTestJSON:test_delete_server_while_in_attached_volume

### ISSUE THREAD

**Issue by liulongzhu** [Hybrid-Cloud/hybrid_cloud#56]
测试用例为：
compute.servers.test_servers_operations.HybridDeleteAwsServersTestJSON.test_delete_server_while_in_attached_volume
报错信息为：
![image](https://cloud.githubusercontent.com/assets/17536495/15416735/3dd359e0-1e81-11e6-9615-8203e764b3a0.png)

**Comment by nash-x** [comment]
现象：用例在创建完虚拟机，创建好卷后，给虚拟机挂卷，挂卷调用AWS接口时，卷的在亚马逊上的状态还没有available，导致失败。
原因：cinder drvier在创建卷的时候，未等待卷available才能返回创建成功。
修改方法：cinder driver.py中create_volume方法中，等待卷available再返回创建成功。

修改记录：
http://202.96.135.238:8081/#/c/203/1
http://202.96.135.238:8081/#/c/204/
