### ISSUE TITLE
performance comparison between ceph and dsware

### ISSUE THREAD

**Issue by arthur-wangfeng** [Hybrid-Cloud/hybrid_cloud#6]
Performance comparison between ceph and dsware.

**deliverables**: comparison report

**due date**: 2015/12/15

**Comment by yinweiishere** [comment]
building hardware testing env.

**Comment by yinweiishere** [comment]
assign to wei to investigate issue: load not pushed to osd, but queued in client, which results in a low random iops (compared with ssd iops).

**Comment by yinweiishere** [comment]
finished.
test report:
https://github.com/Hybrid-Cloud/hybrid_cloud/wiki/Storage-Gateway-Performance-Test-Report
