### ISSUE TITLE
[CI]aws创建虚拟机状态同步耗时很长，偶现无法同步

### ISSUE THREAD

**Issue by liulongzhu** [Hybrid-Cloud/hybrid_cloud#60]

**Comment by nash-x** [comment]
现象：级联层的proxy同步的周期任务_heal_instances_state被_cleanup_running_deleted_instances周期任务阻塞。

这个是openstack同步任务使用绿色线程的一个约束，绿色线程间会相互阻塞。

规避方法：修改如下配置项，将_cleanup_running_deleted_instances关闭。
 # vi /etc/nova/others/cfg_template/nova-proxy.json
            "sync_instance_state_interval": "10",
            "running_deleted_instance_poll_interval": "-1"
