### ISSUE TITLE
[CI]wormhole部署后服务无法启动，配置文件没有更新

### ISSUE THREAD

**Issue by liulongzhu** [Hybrid-Cloud/hybrid_cloud#64]
![image](https://cloud.githubusercontent.com/assets/17536495/15495867/2d9cb4da-21c5-11e6-86aa-5038941136d8.png)

**Comment by llhuii** [comment]
部署目录下etc/没有更新配置文件wormhole.conf, 更新即可

see <del> https://github.com/Hybrid-Cloud/wormhole/commit/259bfde6b0661e1af7b9fb44c4477453142be9d2 </del> https://github.com/Hybrid-Cloud/wormhole/commit/0a10ed3c183af95c0f65e37f2fd58c02eadb7a8d
