### ISSUE TITLE
[CI]hypervm中volume卸载后重新挂载，hypervm内部没有挂载成功

### ISSUE THREAD

**Issue by liulongzhu** [Hybrid-Cloud/hybrid_cloud#67]

**Comment by llhuii** [comment]
Jacket 调用detach-volume之后，路径盘符比如/dev/sdc还存在虚拟机上，需调用echo 1 > /sys/block/sdc/device/delete进行刷新
see https://github.com/Hybrid-Cloud/wormhole/commit/5d21d2c9be2be193b6b093714e74c289ad08933f
