### ISSUE TITLE
[Storage Gateway] IO hook implementation

### ISSUE THREAD

**Issue by yinweiishere** [Hybrid-Cloud/hybrid_cloud#84]
TGT user mode IO hooker implementation:
hook w/r IO from TGT target.

**Comment by yinweiishere** [comment]
status:
analysis done;
3 options to implement iscsi io hook:
1. iscsi qcmd (cons:kernel mode, kernel version dependent, effort big; pros:generic, not dependent on iscsi target implementation)
2. 3.18 after kernel, LIO support user mode iscsi target (pros:LIO is the kernel default iscsi target; cons:kernel version limited, iscsi target dependent)
3. TGT target (pros: user mode, post 2.6 versions supported; cons: TGT is not the kernel default iscsi target)
Consider the implementation simplicity, stability of iscsi target, plus we're in control of iscsi target and kernel, we choose to use option 3.

**Comment by yinweiishere** [comment]
status:
verifying prototype

plan:
finish prototype verification;
implement framework;

**Comment by yinweiishere** [comment]
status:
implemented basic logic;

plan:
commit patch;
check control message interface;
read issue: where to put bloom filter, writer or io hook;

**Comment by yinweiishere** [comment]
plan: performance tool
Performance counter
linux existed tool

**Comment by dsnlevi** [comment]
status:
      introduce lttng  performance tracer tools
      grpc streaming demo test,  compare performance with sendifle
      write a simple snapshot demo

plan:
      read cache design issue

**Comment by yinweiishere** [comment]
IO hook has been implemented already and code completed.
Will track cache issue in another issue;
